### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by xadonxander** [dlo9/LSI-9211-8i-IT-USB#1]
Think you can post a prerequisites to build. All I get is build errors.

**Comment by dlo9** [comment]
@xadonxander the only [build requirement](https://github.com/dlo9/LSI-9211-8i-IT-USB#requirements) should be Docker. Can you post the errors you're receiving?

**Comment by dlo9** [comment]
You're right, the build had several issues since it hasn't been used in two years. I fixed them and added a release artifact in case you don't want to build it yourself.
